repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: pytest -v --cov=app --cov-fail-under=100
        language: system
        pass_filenames: false
        always_run: true
