# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis

        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres

        # Set health checks to wait until postgres has started
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

#    - name: load data into postgres
#      run: pg_restore -d postgres -U postgres -h 127.0.0.1 postgres.dump
#      working-directory: ./data
#      env:
#        PGPASSWORD: postgres

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pipenv
        if [ -f Pipfile ]; then pipenv install --dev --system; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest -v --cache-clear test/

    - name: Create Coverage
      run: |
        pytest -v --cache-clear test/ > pytest-coverage.txt

    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
